import CoverImage from "@/app/blogs/mmtinternship/images/coverimage.webp"
import { Hyperlink } from "@/Components/Link/hyperlink";
import { BlogHeading, BlogParagraph, BlogParagraphEmphasis, BlogSubHeading, BlogImage, BlogParentContainer, EndingNote } from "@/Components/Blogs/blogsComps";

export const metadata = {
    title: "MakeMyTrip Internship",
}

export default function TestBlog() {

    return (
        <>
            <BlogParentContainer>
                <BlogHeading>Learnings as a UX Designer intern at MakeMyTrip</BlogHeading>
                <BlogImage source={CoverImage}></BlogImage>
                <BlogParagraph>Here’s a glimpse of what I learnt during my internship at MakeMyTrip</BlogParagraph>
                <BlogParagraph>First things first, I would like to thank <Hyperlink newTab={true} src={"https://www.linkedin.com/in/stuti-kamboj-85693928/"}>Stuti Kamboj</Hyperlink> and <Hyperlink newTab={true} src={"https://www.linkedin.com/in/u-k-karan-a1202b133/"}>U.K. Karan</Hyperlink> for offering me this opportunity to work with some really good people. I would also like to thank my manager <Hyperlink newTab={true} src={"https://www.linkedin.com/in/kapil-solanki-164166b/"}>Kapil Solanki</Hyperlink> for supporting me throughout my tenure.After an amazing stint at redBus, I decided joined the Go-MMT group once again but this time I worked for MakeMyTrip and GoIbibo flights team.If you want to know about my experience at redBus, do check out the story <Hyperlink newTab={true} src={"https://thevaibhavme.medium.com/my-6-months-internship-experience-at-redbus-262e6abbd1fd?source=post_page-----964d7b38e61f---------------------------------------"}>here</Hyperlink>.</BlogParagraph>
                <BlogParagraph>Going back in timeline to February 2024, the final semester of my undergrad was going on. One day, I was scrolling through LinkedIn and saw a post about Early Check-in UX Design Internship program on Go-MMT Design page. I was very eager to work in big teams and learn from the best, I decided to apply. After a couple of days, I got an email that my portfolio has been shortlisted and the next day I got a call from HR team. After that the interview was scheduled, I cleared it and finally joined the group again on 4th March 2024.</BlogParagraph>
                <BlogParagraphEmphasis>One funny incident happened during the interview: I was asked, “why do you want to come back?” to which I replied, “I want to work in big teams and solve problems in various other LOBs (line of businesses)”. But in the back of my mind, I was thinking I will get a Mac (yes, I’m an Apple fanboy).</BlogParagraphEmphasis>
                <BlogParagraph>The not-so-good part was this internship was planned to in hybrid mode. My college is in Chandigarh and the office is in Gurugram. Sometimes, it became a bit tedious to travel around 6 hours in train to Delhi and then further 2 hours in metro. But, I enjoyed it nonetheless.</BlogParagraph>
                <BlogParagraph>I initially joined MakeMyTrip flights LOB. I worked for 3 months in this LOB and here are a few learnings I would like to share with the audience:</BlogParagraph>
                <BlogSubHeading>Working in big teams is all about stakeholder management</BlogSubHeading>
                <BlogParagraph>Yes, it’s the most important and that’s why I kept it first in the list. Working in big teams is much more about learning how to manage stakeholders than learning design. And yes, sometimes it becomes very difficult to align all the stakeholders and that’s where conflict starts to happen.</BlogParagraph>
                <BlogParagraph>More often than not it happened when I was collaborating with teams like product and engineering. Sometimes, I was able to resolve the conflict on my own and in the most critical times my manager (@Kapil Solanki) helped me a lot in this.</BlogParagraph>
                <BlogParagraph>One simple rule I learnt is to understand the psychology of stakeholders: Why do they want what they want. The difficult part is every stakeholder should be handled differently because their wants will most likely be different from others.</BlogParagraph>
                <BlogSubHeading>Think business then design</BlogSubHeading>
                <BlogParagraph>There are two aspects to it. First, for a company like MMT which has highest market share in flight bookings, even a minor design decision if taken wrongly can affect it’s market share. As a business, our job is to always be at the top. Yes, I have designed a few flows which may not look good as per the conventional wisdom of a designer but we have to ship what the business needs are and not how it looks always.</BlogParagraph>
                <BlogParagraphEmphasis>I remember this quote from Steve Johnson (VP of Design at Netflix) which he quoted in Figma Config 2023, “Design without business is just decoration”. It perfectly holds true in this context.</BlogParagraphEmphasis>
                <BlogParagraph>Second, soon after I receive a problem statement from the product manager, I didn’t open Figma directly and start designing first. I made a natural habit to first understand the business aspects behind the problem statement that I will be solving eventually. And almost 100% of the time, the business and the process is very difficult to understand as there are a lot of things going behind the scenes for booking one single flight ticket.</BlogParagraph>
                <BlogSubHeading>Ask as many questions as possible</BlogSubHeading>
                <BlogParagraph>I cannot emphasize it any more. As I mentioned earlier that booking even one single flight ticket, a lot of complex processes are triggered in the backend and a solid understanding of most of them (if not all) is kind of necessary.</BlogParagraph>
                <BlogParagraph>I had to ask a lot of questions to the stakeholders, even same questions multiple times until and unless I get 100% clarity on the answer. If I didn’t ask, the answer was always no. Asking great questions is an art and not everybody is good at it, even I am also learning to ask great questions. If at any point in time I got stuck while designing, one of the ways to get out of the loop hole is to ask questions from stakeholders.</BlogParagraph>
                <BlogSubHeading>Technology can do anything but not everything</BlogSubHeading>
                <BlogParagraph>Technology can do anything but not everything. If say, I design an interaction which doesn’t exist in the current architecture and introducing it may disturb what is already there in it. I realized it very early that disturbing the architecture on a very large scale would be a disaster and any time, the things can go south.</BlogParagraph>
                <BlogParagraph>We need to understand the limitations of current architecture and build interactions/visuals on top of it. And that’s okay because the scale at which MMT is operating is quite huge and not everything can be implemented which a designer makes, no matter how beautiful it is.</BlogParagraph>
                <BlogSubHeading>Not everything can be solved in version one</BlogSubHeading>
                <BlogParagraph>Given that the product already has a lot of stuff in it, adding new features sometimes was contradictory to what is already there. I worked on two projects in MMT flights LOB centered around the theme of affordable experience. The two flows I designed very contradictory to each other.</BlogParagraph>
                <BlogParagraph>So, prioritizing is the key and more often than not it’s very hard to prioritize features. One simple hack that I had found out is just look at business metric that particular feature would move and the effort required to build that feature. Analyzing the trade off between the two would be a good starting point and it really helps.</BlogParagraph>
                <BlogSubHeading>Take notes and organize Figma files</BlogSubHeading>
                <BlogParagraph>Working in large teams where a lot of back and forth happens, my figma files very often tends to get messy and I the creator of the file was not able to keep track of which iteration was finalized in a meeting.</BlogParagraph>
                <BlogParagraph>I learnt maintaining proper structure of figma files is very important. This not only helps in presenting designs to stakeholder but also in hand-offs when any stakeholder can refer to any design very easily.</BlogParagraph>
                <BlogParagraph>On top of it to keep track of everything, extensively taking notes of the meetings helps to organize stuff. I developed it as a habit but wasn’t able to do it every time. In the long run, it really helps. This made sure I don’t miss out on anything discussed and design process should go seamlessly.</BlogParagraph>
                <BlogParagraph>So, these are a few learning from my time with MakeMyTrip flights team. After 3 months working with this team, I got shifted to GoIbibo flights team and worked 3 months with the new team. My manager (Kapil Solanki) remained the same, the type of projects remained the same. The only thing that changed was the branding and the overall visual theme of the product. Of course, the target audience of the product also changed a bit.</BlogParagraph>
                <BlogParagraph>But nonetheless, the learnings remains the same. After my very first internship at Attentive back in Jun 2022, the next internship I really enjoyed doing was this only. There is something special about this group that if you decide to bid farewell, you’ll keep coming back to it again.</BlogParagraph>
                <BlogParagraphEmphasis>Yes, I have worked with people who are in their second or even third stint with Go-MMT group.</BlogParagraphEmphasis>
                <BlogParagraph>So that’s it for today. Remember, in the long run only two things matter: What you built and who you built it with. In the initial phase of career, I usually insist people to focus on building something good with some really good people. Good amount of money will come as a by-product of this habit. This is something I learnt from the book Build by Tony Fadell (Ex-SVP of iPod division at Apple).</BlogParagraph>
                <BlogParagraph>That’s been my constant learning till now that I will always work with the best of the best people wherever I go.</BlogParagraph>
                <BlogParagraph>Thank you very very much <Hyperlink newTab={true} src={"https://www.linkedin.com/showcase/go-mmt-design/"}>Go-MMT Design</Hyperlink> for offering me a seat at the table.</BlogParagraph>
                <BlogParagraph>If you want to know more about my experience of working with Go-MMT group or need to reach me, feel free to connect on X/Twitter at @realvaibhava. I love to give back to the community.</BlogParagraph>
                {/* <BlogParagraph>stay hungry stay foolish</BlogParagraph> */}
                <EndingNote style={{ paddingTop: "80px" }} />
            </BlogParentContainer>
        </>
    )
}